// Generated by CoffeeScript 1.10.0
(function() {
  var COMMAND;

  COMMAND = {
    gather: 1,
    build: 2
  };

  window.Control = (function() {
    Control.prototype.cursor_x = 1;

    Control.prototype.cursor_y = 1;

    Control.prototype.command = COMMAND.gather;

    Control.prototype.select = false;

    function Control(world, content, renderer) {
      this.world = world;
      this.content = content;
      this.renderer = renderer;
    }

    Control.prototype.translate = function(cursor_x, cursor_y) {
      var tile_height, tile_width, x, y;
      tile_width = this.renderer.tile_width;
      tile_height = this.renderer.tile_height;
      x = ((cursor_x - this.renderer.viewport_offset_x) * .25) - 10;
      y = ((cursor_y - this.renderer.viewport_offset_y) - 100) * this.renderer.zoom;
      return {
        x: Math.round((x / tile_height) + (y / tile_width)),
        y: Math.round((y / tile_width) - (x / tile_height))
      };
    };

    Control.prototype.show_cursor = function(x, y) {
      var height, ix, iy, ox, oy, tile_height, tile_width;
      tile_width = this.renderer.tile_width;
      tile_height = this.renderer.tile_height;
      ix = x * tile_width - (y * tile_width);
      iy = y * tile_height + (x * tile_height);
      ox = x + this.renderer.x_offset;
      oy = y + this.renderer.y_offset;
      height = this.world.map[ox][oy].get_vertical_offset();
      return this.renderer.draw_tile(this.cursor_context, 0, ix, iy, height);
    };

    Control.prototype.init = function() {
      var control_surface, cursor_canvas;
      control_surface = document.getElementById("fx");
      cursor_canvas = document.getElementById("cursor");
      this.cursor_context = cursor_canvas.getContext("2d");
      $(control_surface).mousemove((function(_this) {
        return function(event) {
          var cursor, i, j, ref, ref1, ref2, ref3, x, y;
          _this.cursor_context.clearRect(0, 0, 2000, 2000);
          cursor = _this.translate(event.offsetX, event.offsetY);
          if (_this.select) {
            for (x = i = ref = _this.select.x, ref1 = cursor.x; ref <= ref1 ? i <= ref1 : i >= ref1; x = ref <= ref1 ? ++i : --i) {
              for (y = j = ref2 = _this.select.y, ref3 = cursor.y; ref2 <= ref3 ? j <= ref3 : j >= ref3; y = ref2 <= ref3 ? ++j : --j) {
                _this.show_cursor(x, y);
              }
            }
          } else {
            _this.show_cursor(cursor.x, cursor.y);
          }
          if (_this.move_map) {
            _this.renderer.x_offset = _this.base_offset_x + (_this.move_map.x - cursor.x);
            return _this.renderer.y_offset = _this.base_offset_y + (_this.move_map.y - cursor.y);
          }
        };
      })(this));
      $(control_surface).mousedown((function(_this) {
        return function(event) {
          console.debug(event);
          if (event.button === 0) {
            _this.select = _this.translate(event.offsetX, event.offsetY);
          }
          if (event.button === 2) {
            _this.move_map = _this.translate(event.offsetX, event.offsetY);
            _this.base_offset_x = _this.renderer.x_offset;
            return _this.base_offset_y = _this.renderer.y_offset;
          }
        };
      })(this));
      return $(control_surface).mouseup((function(_this) {
        return function(event) {
          var cursor, end, mouse_x, mouse_y, start;
          cursor = _this.translate(event.offsetX, event.offsetY);
          if (_this.select) {
            start = _this.select;
            end = cursor;
          } else {
            start = cursor;
            end = cursor;
          }
          if (!_this.move_map) {
            start.x = start.x + _this.renderer.x_offset;
            start.y = start.y + _this.renderer.y_offset;
            end.x = end.x + _this.renderer.x_offset;
            end.y = end.y + _this.renderer.y_offset;
            new window.Command(_this.world, start, end, mouse_x = event.pageX, mouse_y = event.pageY);
          }
          _this.select = null;
          return _this.move_map = null;
        };
      })(this));
    };

    return Control;

  })();

}).call(this);

//# sourceMappingURL=control.js.map
