// Generated by CoffeeScript 1.10.0
(function() {
  var Coordinates;

  Coordinates = (function() {
    function Coordinates(x, y) {
      this.x = x;
      this.y = y;
    }

    Coordinates.prototype.equals = function(coordinates) {
      if (coordinates.x === this.x && (coordinates.y = this.y)) {
        return true;
      } else {
        return false;
      }
    };

    return Coordinates;

  })();

}).call(this);

//# sourceMappingURL=coordinates.js.map
