// Generated by CoffeeScript 1.9.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.effects = [];

  window.Effect = (function() {
    Effect.prototype.x = null;

    Effect.prototype.y = null;

    Effect.prototype.tile = null;

    Effect.prototype.lifetime = null;

    Effect.prototype.offset_y = null;

    Effect.prototype.offset_x = null;

    function Effect(x, y) {
      this.x = x;
      this.y = y;
      this.offset_x = 0;
      this.offset_y = 0;
      this.lifetime = 10;
      effects.unshift(this);
    }

    Effect.prototype.run = function() {
      this.lifetime = this.lifetime - 1;
      if (this.lifetime === 0) {
        return this.remove();
      }
    };

    Effect.prototype.remove = function() {
      return window.effects.splice(window.effects.indexOf(this), 1);
    };

    return Effect;

  })();

  window.IndicatorEffect = (function(superClass) {
    extend(IndicatorEffect, superClass);

    function IndicatorEffect(tile, x, y) {
      this.tile = tile;
      IndicatorEffect.__super__.constructor.call(this, x, y);
    }

    IndicatorEffect.prototype.run = function() {
      this.offset_y = this.offset_y - 1;
      return IndicatorEffect.__super__.run.call(this);
    };

    return IndicatorEffect;

  })(Effect);

}).call(this);

//# sourceMappingURL=fx.js.map
