// Generated by CoffeeScript 1.9.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.Location = (function() {
    Location.prototype.y_offset = 0;

    Location.prototype.brightness_variation = 0;

    function Location(world, x, y, height) {
      this.world = world;
      this.x = x;
      this.y = y;
      this.height = height;
      this.brightness_variation = Math.floor(Math.random() * 2);
    }

    Location.prototype.settle = function() {};

    Location.prototype.get_vertical_offset = function() {
      return this.height;
    };

    Location.prototype.around = function(check) {
      var i, ox, oy, results;
      results = [];
      for (ox = i = -1; i <= 1; ox = ++i) {
        results.push((function() {
          var j, results1;
          results1 = [];
          for (oy = j = -1; j <= 1; oy = ++j) {
            if (this.x + ox <= 0) {
              continue;
            }
            if (this.y + oy <= 0) {
              continue;
            }
            if (this.x + ox > this.world.width) {
              continue;
            }
            if (this.y + oy > this.world.height) {
              continue;
            }
            if (ox === 0 && oy === 0) {
              continue;
            }
            results1.push(check(this.world.map[this.x + ox][this.y + oy]));
          }
          return results1;
        }).call(this));
      }
      return results;
    };

    return Location;

  })();

  window.Indicator = (function(superClass) {
    extend(Indicator, superClass);

    function Indicator() {
      return Indicator.__super__.constructor.apply(this, arguments);
    }

    Indicator.prototype.tile = 4;

    return Indicator;

  })(window.Location);

  window.Grass = (function(superClass) {
    extend(Grass, superClass);

    function Grass() {
      return Grass.__super__.constructor.apply(this, arguments);
    }

    Grass.prototype.tile = 3;

    return Grass;

  })(window.Location);

  window.Dirt = (function(superClass) {
    extend(Dirt, superClass);

    function Dirt() {
      return Dirt.__super__.constructor.apply(this, arguments);
    }

    Dirt.prototype.tile = 1;

    return Dirt;

  })(window.Location);

  window.Water = (function(superClass) {
    extend(Water, superClass);

    function Water() {
      return Water.__super__.constructor.apply(this, arguments);
    }

    Water.prototype.tile = 2;

    Water.prototype.get_vertical_offset = function() {
      return (this.world.water_level * 2) - 2;
    };

    return Water;

  })(window.Location);

}).call(this);

//# sourceMappingURL=location.js.map
