// Generated by CoffeeScript 1.10.0
(function() {
  window.Object = (function() {
    Object.prototype.in_pile = false;

    Object.prototype.is_blocking = false;

    Object.prototype.count = 1;

    function Object(world, x, y, count) {
      this.world = world;
      this.x = x;
      this.y = y;
      if (count) {
        this.count = count;
      } else {
        this.count = 1;
      }
    }

    Object.prototype.created = function() {};

    Object.prototype.cycle = function() {};

    Object.prototype.has_product = function() {
      return false;
    };

    return Object;

  })();

}).call(this);

//# sourceMappingURL=object.js.map
