// Generated by CoffeeScript 1.10.0
(function() {
  window.Task = (function() {
    Task.prototype.abbr = null;

    Task.prototype.work = 0;

    Task.prototype.assigned = null;

    Task.prototype.working = null;

    function Task(world, x, y, options) {
      this.world = world;
      this.x = x;
      this.y = y;
      this.id = world.get_id();
      this.working = false;
      if (options) {
        this.options = options;
        this.abbr = this.options.abbr;
        this.work = this.options.work;
        console.log("Set work to:", this.work);
      }
      this.init();
    }

    Task.prototype.remove = function() {
      return this.world.remove_task(this);
    };

    Task.prototype.init = function() {};

    Task.prototype.is_executable = function() {
      return true;
    };

    Task.prototype.execute = function() {};

    Task.prototype.do_work = function() {
      if (this.work > 0) {
        this.work = this.work - 1;
        this.working = true;
        return true;
      }
      return false;
    };

    Task.prototype.get_tile = function() {
      return "command";
    };

    return Task;

  })();

}).call(this);

//# sourceMappingURL=task.js.map
