// Generated by CoffeeScript 1.10.0
(function() {
  window.TemplateLoader = (function() {
    function TemplateLoader() {}

    TemplateLoader.prototype.cache = {};

    TemplateLoader.prototype.get = function(name, callback) {
      var promise, template_uri;
      if (name in this.cache) {
        callback(this.cache[name]);
        return;
      }
      template_uri = "/templates/" + name;
      if (template_uri in window._template_cache) {
        this.cache[name] = _.template(window._template_cache[template_uri]);
        callback(this.cache[name]);
        return;
      }
      promise = $.trafficCop(template_uri);
      return promise.done((function(_this) {
        return function(result) {
          _this.cache[name] = _.template(result);
          return callback(_this.cache[name]);
        };
      })(this));
    };

    return TemplateLoader;

  })();

  window.template_loader = new window.TemplateLoader();

}).call(this);

//# sourceMappingURL=template.js.map
