// Generated by CoffeeScript 1.10.0
(function() {
  window.Utils = {
    distance: function(object1, object2) {
      return Math.abs(object1.x - object2.x) + Math.abs(object2.y, object2.y);
    }
  };

  Array.prototype.insert = function(index, item) {
    return this.splice(index, 0, item);
  };

}).call(this);

//# sourceMappingURL=utils.js.map
