// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.House = (function(superClass) {
    extend(House, superClass);

    function House() {
      return House.__super__.constructor.apply(this, arguments);
    }

    House.prototype.get_tile = function() {
      return 6;
    };

    House.prototype.created = function() {
      this.resident = new window.Worker(this.world, this.x, this.y);
      return this.world.add_actor(this.resident);
    };

    return House;

  })(window.Building);

}).call(this);

//# sourceMappingURL=house.js.map
