// Generated by CoffeeScript 1.9.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.DropTask = (function(superClass) {
    extend(DropTask, superClass);

    function DropTask(world, x, y) {
      DropTask.__super__.constructor.call(this, world, x, y);
    }

    DropTask.prototype.execute = function() {
      var location;
      if (!this.assigned.carry) {
        return false;
      }
      console.log("here");
      if ((!this.world.item_at(this.assigned)) || ((this.world.item_at(this.assigned).constructor === this.assigned.carry.constructor) && this.world.item_at(this.assigned).count < 10)) {
        this.assigned.drop();
        return false;
      }
      location = this.world.find_free_spot(this.assigned.x, this.assigned.y);
      return this.assigned.goto(location);
    };

    return DropTask;

  })(window.Task);

}).call(this);

//# sourceMappingURL=drop.js.map
