// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.RestTask = (function(superClass) {
    extend(RestTask, superClass);

    function RestTask() {
      return RestTask.__super__.constructor.apply(this, arguments);
    }

    RestTask.prototype.is_executable = function() {
      return true;
    };

    RestTask.prototype.execute = function() {
      var bed;
      if (this.carry) {
        return new window.DropTask(this.world, this.x, this.y);
      }
      if (this.world.item_at(this.assigned) instanceof window.Bed) {
        console.log("Sleeping");
        if (this.do_work()) {
          return true;
        }
        this.assigned.sleep = 0;
        return false;
      }
      bed = this.world.find_item(this.x, this.y, window.Bed, null);
      if (!bed) {
        return false;
      }
      if (!this.world.is_reachable(bed)) {
        return false;
      }
      this.assigned.goto(bed);
      return true;
    };

    return RestTask;

  })(window.Task);

}).call(this);

//# sourceMappingURL=rest.js.map
