// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.Potato = (function(superClass) {
    extend(Potato, superClass);

    function Potato() {
      return Potato.__super__.constructor.apply(this, arguments);
    }

    Potato.prototype.name = "potato";

    Potato.prototype.planted = window.PotatoPlant;

    Potato.prototype.get_tile = function() {
      return "potato";
    };

    Potato.prototype.get_planted = function() {
      return window.PotatoPlant;
    };

    return Potato;

  })(window.Food);

}).call(this);

//# sourceMappingURL=potato.js.map
