// Generated by CoffeeScript 1.9.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.PotatoPlant = (function(superClass) {
    extend(PotatoPlant, superClass);

    function PotatoPlant() {
      return PotatoPlant.__super__.constructor.apply(this, arguments);
    }

    PotatoPlant.prototype.name = "potato_plant";

    PotatoPlant.prototype.grow_delay = 50;

    PotatoPlant.prototype.get_product = function() {
      PotatoPlant.__super__.get_product.call(this);
      return window.Potato;
    };

    PotatoPlant.prototype.get_tile = function() {
      if (this.grown === this.grow_delay) {
        return "potato_plant";
      } else {
        return "potato_plant_growing";
      }
    };

    return PotatoPlant;

  })(window.Plant);

}).call(this);

//# sourceMappingURL=potato_plant.js.map
