// Generated by CoffeeScript 1.9.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.Wood = (function(superClass) {
    extend(Wood, superClass);

    function Wood() {
      return Wood.__super__.constructor.apply(this, arguments);
    }

    Wood.prototype.name = "wood";

    Wood.prototype.get_tile = function() {
      return 8;
    };

    return Wood;

  })(window.Object);

}).call(this);

//# sourceMappingURL=wood.js.map
