// Generated by CoffeeScript 1.9.2
(function() {
  window.EngineTest = (function() {
    function EngineTest(world) {
      this.world = world;
    }

    EngineTest.prototype.execute = function() {};

    return EngineTest;

  })();

}).call(this);

//# sourceMappingURL=base.js.map
