// Generated by CoffeeScript 1.9.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.BuildTest = (function(superClass) {
    extend(BuildTest, superClass);

    function BuildTest() {
      return BuildTest.__super__.constructor.apply(this, arguments);
    }

    BuildTest.prototype.execute = function() {
      var i, j, options, results;
      options = {
        needs: [
          {
            material: window.Wood,
            count: 3
          }
        ],
        result: window.House,
        abbr: "H"
      };
      this.world.add_task(new window.BuildTask(this.world, 8, 7, options));
      this.world.add_item(new window.House(this.world, 8, 10));
      results = [];
      for (i = j = 1; j <= 10; i = ++j) {
        results.push(this.world.add_item(new window.Wood(this.world, 11, 6 + i)));
      }
      return results;
    };

    return BuildTest;

  })(window.EngineTest);

}).call(this);

//# sourceMappingURL=build.js.map
