// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.HarvestTest = (function(superClass) {
    extend(HarvestTest, superClass);

    function HarvestTest() {
      return HarvestTest.__super__.constructor.apply(this, arguments);
    }

    HarvestTest.prototype.execute = function() {
      this.world.items[10][10] = new Wheat(this.world, 10, 10);
      this.world.add_task(new window.GatherTask(this.world, 10, 10, {
        abbr: "H"
      }));
      return this.world.add_item(new window.House(this.world, 8, 10));
    };

    return HarvestTest;

  })(window.EngineTest);

}).call(this);

//# sourceMappingURL=harvest.js.map
